solon.app:
    name: zyf-biz
    group: com.xunmo
server.port: 8081


test.db1:
    schema: rock
    jdbcUrl: jdbc:mysql://localhost:3306/railway_bureau_test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&stringtype=unspecified&allowMultiQueries=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root

#默认
mybatis.db1:
    typeAliases:    #支持包名 或 类名（.class 结尾）
        - "com.xunmo.webs.*.entity"
    mappers:        #支持包名 或 类名（.class 结尾）或 xml（.xml结尾 或 *.xml 结尾）
        - "mybatis/db1/*.xml"
#        - "com.xunmo.webs.*.mapper"
